Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2337059] Child process with pid: 2337064 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2337447] Child process with pid: 2337453 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2337447] Child process with pid: 2337461 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2338783] Child process with pid: 2338785 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2338783] Child process with pid: 2338786 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2338783] Child process with pid: 2338798 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2338801] Child process with pid: 2338803 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2338801] Child process with pid: 2339125 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2339791] Child process with pid: 2339794 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2343021] Child process with pid: 2343023 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2346327] Child process with pid: 2346334 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2346327] Child process with pid: 2346344 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[UID:2385][2346748] Child process with pid: 2346754 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:2385][2347626] Child process with pid: 2347631 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:2385][2347626] Child process with pid: 2347644 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:2385][2347626] Child process with pid: 2347656 was killed by signal: 15, core dumped: no
Traceback (most recent call last):
  File "/home/saeidab1/mehr/passenger_wsgi.py", line 16, in <module>
    from core.wsgi import application
  File "/home/saeidab1/mehr/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:2385][2347626] Child process with pid: 2348470 was killed by signal: 15, core dumped: no
Internal Server Error: /
Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: config_config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/saeidab1/mehr/default/views.py", line 44, in HomePage
    return render(request, 'index.html', context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/opt/alt/python39/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 26, in render
    'g_configs': load_configs()
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 10, in load_configs
    for config in configs:
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: config_config
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: config_config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/saeidab1/mehr/default/views.py", line 44, in HomePage
    return render(request, 'index.html', context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/opt/alt/python39/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 26, in render
    'g_configs': load_configs()
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 10, in load_configs
    for config in configs:
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: config_config
Internal Server Error: /
Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: config_config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/saeidab1/mehr/default/views.py", line 44, in HomePage
    return render(request, 'index.html', context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/opt/alt/python39/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 26, in render
    'g_configs': load_configs()
  File "/home/saeidab1/mehr/default/default_context_processor.py", line 10, in load_configs
    for config in configs:
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: config_config
Invalid HTTP_HOST header: 'saeidabbaszadeh.site'. You may need to add 'saeidabbaszadeh.site' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'saeidabbaszadeh.site'. You may need to add 'saeidabbaszadeh.site' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'saeidabbaszadeh.site'. You may need to add 'saeidabbaszadeh.site' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/saeidab1/virtualenv/mehr/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'saeidabbaszadeh.site'. You may need to add 'saeidabbaszadeh.site' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /server
Not Found: /.vscode/sftp.json
Not Found: /about
Not Found: /server
Not Found: /.vscode/sftp.json
Not Found: /about
Not Found: /debug/default/view
Not Found: /v2/_catalog
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
Not Found: /server-status
Not Found: /debug/default/view
Not Found: /login.action
Not Found: /_all_dbs
Not Found: /v2/_catalog
Not Found: /.DS_Store
Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
Not Found: /.env
Not Found: /s/530313e2830323e2238313e2731323/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
Not Found: /config.json
Not Found: /telescope/requests
Not Found: /server-status
Not Found: /login.action
Not Found: /_all_dbs
Not Found: /.DS_Store
Not Found: /.env
Not Found: /s/530313e2830323e2238313e2731323/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
Not Found: /config.json
Not Found: /telescope/requests
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2378313] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
slide/product/kasper.html
slide/product/esset.html
Not Found: /favicon.ico
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2551661] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 7, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
[UID:2385][2606465] Reached max children process limit: 6, extra: 2, current: 8, busy: 8, please increase LSAPI_CHILDREN.
